<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
      <UserSecretsId>0c11c313-0cef-4244-9418-e6a50410b8c9</UserSecretsId>
  </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\service\service.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="NSwag.AspNetCore" Version="14.7.1" />
    </ItemGroup>

</Project>
